---
apiVersion: v1
kind: Service
metadata:
  name: testelixir
  namespace: media-cloud-ai
  labels:
    run: testelixir
spec:
  ports:
  - port: 80
    protocol: TCP
    name: testelixir
  selector:
    name: testelixir